<?php
$servername = "serverName";
$username = "userName";
$password = "password";
$dbname = "dbName";

//We collect all data sent by the user
$jsonArrayDesc=json_decode($_GET['jsonArrayDesc']);
$jsonArrayCandidate1Pos =json_decode($_GET['jsonArrayCandidate1Pos']);
$jsonArrayCandidate2Pos =json_decode($_GET['jsonArrayCandidate2Pos']);
$candidate1Name=$_GET['candidate1Name'];
$candidate2Name=$_GET['candidate2Name'];
$questionnaireTitle=$_GET['questionnaireTitle'];
$fullLength=count($jsonArrayDesc);

//Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);

//This function return the new proposition_ID we will use depending of the highest proposition_ID in the table
function getMaxPropID($conn) {
    $sql1="SELECT MAX(proposition_ID) as maximum FROM proposition_info";
    $propositionID = mysqli_query($conn,$sql1);
    $propositionID2 = mysqli_fetch_array($propositionID);
    $max=$propositionID2["maximum"]+1;
    return $max;
}
//This function return the new questionnary_ID we will use depending of the highest questionnary_ID in the table
function getMaxQuestionnaryID($conn) {
    $sql1="SELECT MAX(questionnary_ID) as maximum FROM questionnary_info";
    $questionnaryID = mysqli_query($conn,$sql1);
    $questionnaryID2 = mysqli_fetch_array($questionnaryID);
    $max=$questionnaryID2["maximum"]+1;
    return $max;
}
//This function return the new candidate_ID we will use depending of the highest candidate_ID in the table
function getMaxCandidateID($conn) {
    $sql1="SELECT MAX(candidate_ID) as maximum FROM candidate_info";
    $candidateID = mysqli_query($conn,$sql1);
    $candidateID2 = mysqli_fetch_array($candidateID);
    $max=$candidateID2["maximum"]+1;
    return $max;
}
//This function is used to fill the table questionnaire_info
function fillQuestionnaire_info($conn,$questionnaireTitle){
    $sql="SELECT * FROM questionnary_info WHERE description='".$questionnaireTitle."'";
    $result = mysqli_query($conn,$sql);
    if (mysqli_num_rows($result) > 0) {
    // if the questionnaire title we do nothing, but this case should never happen because it's handled in the javascript
    } else {
	//we create a new row, with a new questionnary_ID generated by the function getMaxQuestionnaryID
   	$newQuestionnaireID=getMaxQuestionnaryID($conn);
	//We add the row to the table
	$sqlInsert = "INSERT INTO questionnary_info(questionnary_ID,description,displayed) VALUES ('$newQuestionnaireID', '$questionnaireTitle', 0)";
	if (mysqli_query($conn,$sqlInsert) === TRUE) {
		//we return the newQuestionnaireID to use it later
		return $newQuestionnaireID;
	} else {
	}    
    }
}
//This function fill the table proposition_info
function fillProposition_info($conn,$jsonArrayDesc,$fullLength){
	$propositionID=array();
	//we create as many row as the user create new proposition
	for($x=0;$x<$fullLength;$x++){
	    $desc=$jsonArrayDesc[$x];     
	    //We check if the proposition already exist in the table
	    $sql="SELECT proposition_ID FROM proposition_info WHERE description='".$desc."'";
	    $result = mysqli_query($conn,$sql);
	    if (mysqli_num_rows($result) > 0) {
	    // if it already exist, we get the ID of the proposition already existing
		$propID=mysqli_fetch_array($result);
		//we store it in an array we will use later
		$propositionID[$x]=$propID['proposition_ID'];
	        
	    } else {
		//if it doesn't exist we create a new row in the table
		$propDesc=$jsonArrayDesc[$x];
		//we generate a new proposition_ID
	   	$newPropositionID=getMaxPropID($conn);
		// we create a new row with the proposition created by the user and the new ID generated
		$sqlInsert = "INSERT INTO proposition_info(proposition_ID,description) VALUES ('$newPropositionID', '$propDesc')";
	    	if (mysqli_query($conn,$sqlInsert) === TRUE) {
			//we store the ID generated in the array to use it later
			$propositionID[$x]=$newPropositionID;
		} else {
		}
	    }
      	}
	//we return the array with all the proposition_ID to use it later
	return $propositionID;
}
//This function fill the questionnaire table
function fillQuestionnaire($conn,$newQuestionnaryID,$propositionID,$fullLength){
	//we use the propositionID created int the function above, and the questionnaryID we generated
	//we create as many row as the user wants proposition in the questionnaire
	for($x=0;$x<$fullLength;$x++){
		$var1=$propositionID[$x];
		$sql="INSERT INTO questionnary(questionnary_ID,proposition_ID) VALUES ('$newQuestionnaryID','$var1')";
		if (mysqli_query($conn,$sql) === TRUE) {
		} else {
		}
	}
}


//This function fill the candidate_info table
function fillCandidate_info($conn,$candidate1Name,$candidate2Name){
	$candidateArray=array($candidate1Name,$candidate2Name);
	$candidateID=array();
	//Only two candidate can be created(depending if one already exist in the database)
	for($x=0;$x<2;$x++){
	    $name=$candidateArray[$x];
	    //We check if a candidate already exists in the database
	    $sql="SELECT candidate_ID FROM candidate_info WHERE candidate_name='".$name."'";
	    $result = mysqli_query($conn,$sql);
	    if (mysqli_num_rows($result) > 0) {
	    // if it exist we don't create a new row, and we store the candidate_ID already existing
		$candID=mysqli_fetch_array($result);
		$candidateID[$x]=$candID['candidate_ID'];
	        
	    } else {
		//if it doesn't exist we generate a new candidate_ID using getMaxCandidateID
	   	$newCandidateID=getMaxCandidateID($conn);
		//We create a new row using the candidateName provided by the user, and the ID generated
		$sqlInsert = "INSERT INTO candidate_info(candidate_ID,candidate_name) VALUES ('$newCandidateID', '$name')";
	    	if (mysqli_query($conn,$sqlInsert) === TRUE) {
			//we store the ID generated in the array
			$candidateID[$x]=$newCandidateID;
		} else {
		}
	    }
      	}
	//we return the array which is used later
	return $candidateID;
}
//this function fill the candidate_position table
function fillCandidate_position($conn,$candidateID,$propositionID,$fullLength,$jsonArrayCandidate1Pos,$jsonArrayCandidate2Pos){
	//We use two for loop, because there are two candidate
	for($x=0;$x<$fullLength;$x++){
	    $canID=$candidateID[0];
	    $propID=$propositionID[$x];
	    //We check if the combination of the candidate_ID and the proposition_ID are already in the table
	    $sql="SELECT * FROM candidate_position WHERE candidate_ID='".$canID."' AND proposition_ID='".$propID."'";
	    $result = mysqli_query($conn,$sql);
	    if (mysqli_num_rows($result) > 0) {
	        //if they are we do nothing
	    } else {
		//if they are not we create a new row
		$pos=intval($jsonArrayCandidate1Pos[$x]);
		//we create the row using the candidateID, the propID, and the position provided by the user
		$sqlInsert = "INSERT INTO candidate_position(candidate_ID,proposition_ID,Position) VALUES ('$canID', '$propID','$pos')";
		if (mysqli_query($conn,$sqlInsert) === TRUE) {
		} else {
		}
	    }
      	}
	for($x=0;$x<$fullLength;$x++){
	    $canID=$candidateID[1];
	    $propID=$propositionID[$x];
	    //We check if the combination of the candidate_ID and the proposition_ID are already in the table
	    $sql="SELECT * FROM candidate_position WHERE candidate_ID='".$canID."' AND proposition_ID='".$propID."'";
	    $result = mysqli_query($conn,$sql);
	    if (mysqli_num_rows($result) > 0) {
	        //if they are we do nothing
	    } else {
		//if they are not we create a new row
		$pos=$jsonArrayCandidate2Pos[$x];
		$sqlInsert = "INSERT INTO candidate_position(candidate_ID,proposition_ID,Position) VALUES ('$canID', '$propID','$pos')";
	    	//we create the row using the candidateID, the propID, and the position provided by the user
		if (mysqli_query($conn,$sqlInsert) === TRUE) {
		} else {
		}
	    }
      	}
}

//We call all the function created in the good order to fill all the 5 tables on the database
$newQuestionnaireID=fillQuestionnaire_info($conn,$questionnaireTitle);
$propositionID=fillProposition_info($conn,$jsonArrayDesc,$fullLength);
fillQuestionnaire($conn,$newQuestionnaireID,$propositionID,$fullLength);
$candidateID=fillCandidate_info($conn,$candidate1Name,$candidate2Name);
fillCandidate_position($conn,$candidateID,$propositionID,$fullLength,$jsonArrayCandidate1Pos,$jsonArrayCandidate2Pos);

//we close the connection
mysqli_close($conn);
?>
